apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: zomato-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: vero026/zomato-order-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8003

        env:
        - name: MONGODB_URL
          value: mongodb://mongodb-order:27017
        - name: DATABASE_NAME
          value: order_db
        - name: SECRET_KEY
          value: zomato-super-secret-key-change-in-production-2024