apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: zomato-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      initContainers:
      - name: wait-for-mongo
        image: busybox
        command: ['sh', '-c', 'until nc -z mongodb-user 27017; do echo waiting for mongodb; sleep 2; done']

      containers:
      - name: user-service
        image: vero026/zomato-user-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8001

        env:
        - name: MONGODB_URL
          value: mongodb://mongodb-user:27017
        - name: DATABASE_NAME
          value: user_db
        - name: SECRET_KEY
          value: zomato-super-secret-key-change-in-production-2024

        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 10
          periodSeconds: 5

        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 20
          periodSeconds: 10