apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
  namespace: zomato-dev
spec:
  selector:
    app: restaurant-service
  ports:
    - port: 5001
      targetPort: 5001
  type: ClusterIP