apiVersion: apps/v1
kind: Deployment
metadata:
  name: zomato-frontend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: zomato-frontend
  template:
    metadata:
      labels:
        app: zomato-frontend
    spec:
      containers:
      - name: frontend
        image: {{ .Values.frontend.image }}:{{ .Values.frontend.tag }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.frontend.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: zomato-frontend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: zomato-frontend
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
  type: ClusterIP
