apiVersion: apps/v1
kind: Deployment
metadata:
  name: zomato-nginx
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.nginx.replicas }}
  selector:
    matchLabels:
      app: zomato-nginx
  template:
    metadata:
      labels:
        app: zomato-nginx
    spec:
      containers:
      - name: nginx
        image: {{ .Values.nginx.image }}:{{ .Values.nginx.tag }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.nginx.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: zomato-nginx
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: zomato-nginx
  ports:
    - port: {{ .Values.nginx.port }}
      targetPort: {{ .Values.nginx.port }}
  type: {{ .Values.nginx.serviceType }}
